###
POST http://localhost:2000/api/usuarios HTTP/1.1
Content-Type: application/json


{
    "name": "Ismael",
    "lastname": "Salazar",
    "address": "Quito",
    "ci": 1727284554
}

GET http://localhost:2000/api/usuarios HTTP/1.1