###
POST http://localhost:8080/api/productos HTTP/1.1

###
GET http://localhost:8080/api/productos HTTP/1.1

###
GET http://localhost:8080/api/productos/Pera HTTP/1.1

###
DELETE http://localhost:8080/api/productos/Sandia HTTP/1.1

###
PUT http://localhost:8080/api/productos/Aguacate HTTP/1.1




