###
POST http://localhost:2000/api/usuarios HTTP/1.1
Content-Type: application/json

{
    "name": "Joel",
    "lastname": "Peres",
    "address": "Manta",
    "ci": 1725364792
}

###
GET http://localhost:2000/api/usuarios HTTP/1.1

###
GET http://localhost:2000/api/usuarios/1765378913 HTTP/1.1

###
DELETE http://localhost:2000/api/usuarios/62aad50de809af36c5785e49 HTTP/1.1

###
PUT http://localhost:2000/api/usuarios/62aad50efaa5cfba70effcd0 HTTP/1.1
Content-Type: application/json

{
    "name": "David",
    "lastname": "Parker",
    "address": "Manabi",
    "ci": 1765378913
}