###
POST http://localhost:2000/api/proveedores HTTP/1.1
content-type:application/json

{
  "name" : "PollosPrimos",
  "city": "Quito",
  "discount" : 14
}

###
GET http://localhost:2000/api/proveedores HTTP/1.1

###
GET http://localhost:2000/api/proveedores/62aa5aaa353d3d98030d3d19 HTTP/1.1

###
DELETE http://localhost:2000/api/proveedores/62aa5a81353d3d98030d3d17 HTTP/1.1

###
PUT http://localhost:2000/api/proveedores/62aa5aaa353d3d98030d3d19 HTTP/1.1
Content-Type: application/json


{
  "name": "La Moderna",
  "city": "Ambato",
  "discount": 17
}